import { InventoryItem, ProductInventoryMapping } from '../../types/admin';

export const DEFAULT_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'INV-FRM-5X7',
    name: '5×7 Solid Wood Frame Moulding',
    category: 'Frames',
    unit: 'pcs',
    currentStock: 45,
    minimumStock: 10,
    purchaseCost: 65,
    supplier: 'Bengal Timber & Moulding Co, Bowbazar',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-FRM-6X8',
    name: '6×8 Solid Wood Frame Moulding',
    category: 'Frames',
    unit: 'pcs',
    currentStock: 50,
    minimumStock: 15,
    purchaseCost: 78,
    supplier: 'Bengal Timber & Moulding Co, Bowbazar',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-FRM-8X10',
    name: '8×10 Solid Wood Frame Moulding',
    category: 'Frames',
    unit: 'pcs',
    currentStock: 35,
    minimumStock: 10,
    purchaseCost: 110,
    supplier: 'Bengal Timber & Moulding Co, Bowbazar',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-FRM-10X12',
    name: '10×12 Solid Wood Frame Moulding',
    category: 'Frames',
    unit: 'pcs',
    currentStock: 25,
    minimumStock: 8,
    purchaseCost: 145,
    supplier: 'Bengal Timber & Moulding Co, Bowbazar',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-FRM-12X18',
    name: '12×18 Solid Wood Frame Moulding',
    category: 'Frames',
    unit: 'pcs',
    currentStock: 18,
    minimumStock: 6,
    purchaseCost: 195,
    supplier: 'Bengal Timber & Moulding Co, Bowbazar',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-GLS-5X7',
    name: '5×7 Protective Float Glass',
    category: 'Frames',
    unit: 'pcs',
    currentStock: 60,
    minimumStock: 15,
    purchaseCost: 20,
    supplier: 'Calcutta Glass Merchants, College St',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-GLS-6X8',
    name: '6×8 Protective Float Glass',
    category: 'Frames',
    unit: 'pcs',
    currentStock: 55,
    minimumStock: 15,
    purchaseCost: 25,
    supplier: 'Calcutta Glass Merchants, College St',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-GLS-8X10',
    name: '8×10 Protective Float Glass',
    category: 'Frames',
    unit: 'pcs',
    currentStock: 40,
    minimumStock: 10,
    purchaseCost: 35,
    supplier: 'Calcutta Glass Merchants, College St',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-GLS-10X12',
    name: '10×12 Protective Float Glass',
    category: 'Frames',
    unit: 'pcs',
    currentStock: 30,
    minimumStock: 8,
    purchaseCost: 45,
    supplier: 'Calcutta Glass Merchants, College St',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-GLS-12X18',
    name: '12×18 Protective Float Glass',
    category: 'Frames',
    unit: 'pcs',
    currentStock: 20,
    minimumStock: 5,
    purchaseCost: 65,
    supplier: 'Calcutta Glass Merchants, College St',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-PPR-LUSTER',
    name: '240 GSM Luster Photo Paper',
    category: 'Photo Paper',
    unit: 'sheets',
    currentStock: 150,
    minimumStock: 30,
    purchaseCost: 15,
    supplier: 'Kolkata Graphic Papers, Chandni Chowk',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-PPR-VELVET',
    name: '280 GSM Studio Velvet Satin Paper',
    category: 'Photo Paper',
    unit: 'sheets',
    currentStock: 100,
    minimumStock: 25,
    purchaseCost: 28,
    supplier: 'Kolkata Graphic Papers, Chandni Chowk',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-PPR-ARCHIVAL',
    name: '310 GSM Archival Fine Art Cotton Rag',
    category: 'Photo Paper',
    unit: 'sheets',
    currentStock: 60,
    minimumStock: 15,
    purchaseCost: 55,
    supplier: 'Kolkata Graphic Papers, Chandni Chowk',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-STK-VINYL',
    name: 'Satin Vinyl Waterproof Sticker Sheets',
    category: 'Sticker Paper',
    unit: 'sheets',
    currentStock: 120,
    minimumStock: 25,
    purchaseCost: 18,
    supplier: 'Apex Vinyl Imports, Burrabazar',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-PKG-FRM',
    name: 'Reinforced Frame Box & Corner Protectors',
    category: 'Packaging',
    unit: 'boxes',
    currentStock: 90,
    minimumStock: 20,
    purchaseCost: 22,
    supplier: 'Metro Corrugated Cartons, Sealdah',
    active: true,
    lastUpdated: '2026-09-29',
  },
  {
    id: 'INV-PKG-STK',
    name: 'Rigid Non-Bending Sticker Mailer',
    category: 'Packaging',
    unit: 'pcs',
    currentStock: 140,
    minimumStock: 30,
    purchaseCost: 8,
    supplier: 'Metro Corrugated Cartons, Sealdah',
    active: true,
    lastUpdated: '2026-09-29',
  },
];

export const DEFAULT_PRODUCT_MAPPINGS: ProductInventoryMapping[] = [
  {
    id: 'MAP-FRM-5X7',
    productType: 'custom-photo-frames',
    productName: 'Custom Photo Frames',
    sizeName: '5×7 in',
    consumes: [
      { inventoryItemId: 'INV-FRM-5X7', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-GLS-5X7', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PPR-LUSTER', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PKG-FRM', quantityPerUnit: 1 },
    ],
  },
  {
    id: 'MAP-FRM-6X8',
    productType: 'custom-photo-frames',
    productName: 'Custom Photo Frames',
    sizeName: '6×8 in',
    consumes: [
      { inventoryItemId: 'INV-FRM-6X8', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-GLS-6X8', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PPR-LUSTER', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PKG-FRM', quantityPerUnit: 1 },
    ],
  },
  {
    id: 'MAP-FRM-8X10',
    productType: 'custom-photo-frames',
    productName: 'Custom Photo Frames',
    sizeName: '8×10 in',
    consumes: [
      { inventoryItemId: 'INV-FRM-8X10', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-GLS-8X10', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PPR-LUSTER', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PKG-FRM', quantityPerUnit: 1 },
    ],
  },
  {
    id: 'MAP-FRM-10X12',
    productType: 'custom-photo-frames',
    productName: 'Custom Photo Frames',
    sizeName: '10×12 in',
    consumes: [
      { inventoryItemId: 'INV-FRM-10X12', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-GLS-10X12', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PPR-LUSTER', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PKG-FRM', quantityPerUnit: 1 },
    ],
  },
  {
    id: 'MAP-FRM-12X18',
    productType: 'custom-photo-frames',
    productName: 'Custom Photo Frames',
    sizeName: '12×18 in',
    consumes: [
      { inventoryItemId: 'INV-FRM-12X18', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-GLS-12X18', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PPR-LUSTER', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PKG-FRM', quantityPerUnit: 1 },
    ],
  },
  {
    id: 'MAP-STK-SMALL',
    productType: 'photo-stickers',
    productName: 'Photo Stickers',
    sizeName: 'Small',
    consumes: [
      { inventoryItemId: 'INV-STK-VINYL', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PKG-STK', quantityPerUnit: 1 },
    ],
  },
  {
    id: 'MAP-STK-MEDIUM',
    productType: 'photo-stickers',
    productName: 'Photo Stickers',
    sizeName: 'Medium',
    consumes: [
      { inventoryItemId: 'INV-STK-VINYL', quantityPerUnit: 1 },
      { inventoryItemId: 'INV-PKG-STK', quantityPerUnit: 1 },
    ],
  },
  {
    id: 'MAP-STK-LARGE',
    productType: 'photo-stickers',
    productName: 'Photo Stickers',
    sizeName: 'Large',
    consumes: [
      { inventoryItemId: 'INV-STK-VINYL', quantityPerUnit: 2 },
      { inventoryItemId: 'INV-PKG-STK', quantityPerUnit: 1 },
    ],
  },
];
